package com.ivanconsalter.algamoney.security;

public enum AuthorityEnum {
	
	ROLE_CADASTRAR_CATEGORIA, 
	ROLE_PESQUISAR_CATEGORIA,

	ROLE_CADASTRAR_PESSOA,
	ROLE_REMOVER_PESSOA,
	ROLE_PESQUISAR_PESSOA,

	ROLE_CADASTRAR_LANCAMENTO,
	ROLE_REMOVER_LANCAMENTO,
	ROLE_PESQUISAR_LANCAMENTO,

}
